name: GCR

on: 
  push:
     branches:    
      - 'victor-main'

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
    
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Build the hello-docker Docker image
      run: |
        docker build . --tag ghcr.io/deselikem/hello-docker-gcr-demo:latest
        docker run ghcr.io/deselikem/hello-docker-gcr-demo:latest
        docker push ghcr.io/deselikem/hello-docker-gcr-demo:latest